spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23liKEHwxQwHwZe7Nv
            clientSecret: 6b11eeb028fc048ddfe1baec930d05ccda98f9ae
            
server:
  port: 8081           

